#!/bin/bash

set -e 

d=`pwd`
cid=`docker run -i -d -v ${d}:/q q-text-as-data-rpm-builder:0.1`

function kill_container {
	tmp=`docker kill ${cid}`
}
trap kill_container EXIT

sleep 1
docker exec -it ${cid} /bin/bash -i -c "/q/dist/create-rpm $1 $2"

docker cp ${cid}:/q/dist/rpm_build_area/RPMS/noarch/q-text-as-data-1.6.0-1.el6.noarch.rpm ./
