#!/bin/bash

set -e 

base_folder=$(dirname $0)
pushd ${base_folder} >/dev/null

if [ $# -ne 2 ];
then
	echo "Usage: $(dirname $0) <version> <git-tag>"
	echo
	echo "Note that the git tag must be pushed to github before doing this."
	exit 1
fi
VERSION="$1"
BASED_ON_TAG="$2"

echo uploading
gh release upload 2.0.18 ./packages/*.{rpm,deb}

echo done



